[package]
name = "task_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
serde_json = "1.0.127"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
serde = { version = "1.0.209", features = ["derive"] }
